users:

  nik:
    setwd: "C:/Users/nbartlome/OneDrive/1_Universität/4_PhD/10_R with R/Shiny R/ClimeApp_all/ClimeApp"
    lib_path: "C:/Users/nbartlome/OneDrive/ClimeApp_all/ClimeApp/library"
  
  richard:
    setwd: "C:/Users/Richard/OneDrive/ClimeApp_all/ClimeApp"
    lib_path: "C:/Users/rw22z389/OneDrive/ClimeApp_all/ClimeApp/library"
  
  noemie:
    setwd: "C:/Users/noemi/OneDrive/ClimeApp_all/ClimeApp"
    lib_path: "C:/Users/nw22d367/OneDrive/ClimeApp_all/ClimeApp/library"
  
  tanja:
    setwd: "C:/Users/tanja/OneDrive/ClimeApp_all/ClimeApp"
    lib_path: "C:/Users/tanja/OneDrive/ClimeApp_all/ClimeApp/library"
    
################################################################################
danach in app.R einfügen:

library(config)

# Lade die Konfiguration
config <- config::get(file = "config.yml")

# Benutzername abrufen und Konfiguration anwenden, wie zuvor erklärt
username <- Sys.getenv("USERNAME")

if (username %in% names(config$users)) {
  user_config <- config$users[[username]]
  setwd(user_config$setwd)
  assign(".lib.loc", user_config$lib_path, envir = environment(.libPaths))
} else {
  stop("Benutzername nicht in der Konfigurationsdatei gefunden.")
}